added more steps.

diff --git a/.github/workflows/infra-ci-cd.yml b/.github/workflows/infra-ci-cd.yml
--- a/.github/workflows/infra-ci-cd.yml
+++ b/.github/workflows/infra-ci-cd.yml
@@ -67,4 +67,35 @@ jobs:
     - uses: actions/checkout@v4
       name: Checkout
     
+    # Install the latest version of the Terraform CLI
+    - uses: hashicorp/setup-terraform@v3
+      name: Setup Terraform
+      with:
+        terraform_wrapper: false
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      run: terraform init
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
+
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
     
+        if [ $exitcode -eq 1 ]; then
+            echo Terraform Plan Failed!
+            exit 1
+        else 
+            exit 0
+        fi
+      
